//! Shared Light and Dark UI tokens. Edit these values directly.

/// Immutable value for the same semantic role in both appearances.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DesignToken {
    pub name: &'static str,
    pub token_type: &'static str,
    pub light: &'static str,
    pub dark: &'static str,
}

/// Resolved, framework-neutral Light and Dark values used by production UI.
///
/// This is deliberately a semantic subset of the source export: it contains
/// every appearance-dependent semantic role plus shared layout and type roles.
pub const TOKENS: &[DesignToken] = &[
    DesignToken {
        name: "color.canvas.application",
        token_type: "color",
        light: "#F6F8F7",
        dark: "#151713",
    },
    DesignToken {
        name: "color.divider",
        token_type: "color",
        light: "#D7DED9",
        dark: "#374039",
    },
    DesignToken {
        name: "color.border.default",
        token_type: "color",
        light: "#D7DED9",
        dark: "#465048",
    },
    DesignToken {
        name: "color.border.strong",
        token_type: "color",
        light: "#818D85",
        dark: "#6E7A71",
    },
    DesignToken {
        name: "color.focus.ring",
        token_type: "color",
        light: "#3578B8",
        dark: "#73B7F0",
    },
    DesignToken {
        name: "color.surface.sidebar",
        token_type: "color",
        light: "#FAFBFA",
        dark: "#1A1D19",
    },
    DesignToken {
        name: "color.surface.panel",
        token_type: "color",
        light: "#FFFFFF",
        dark: "#20231F",
    },
    DesignToken {
        name: "color.surface.manuscript",
        token_type: "color",
        light: "#FFFFFF",
        dark: "#252924",
    },
    DesignToken {
        name: "color.surface.elevated",
        token_type: "color",
        light: "#FFFFFF",
        dark: "#2A2F29",
    },
    DesignToken {
        name: "color.surface.sunken",
        token_type: "color",
        light: "#EDF1EE",
        dark: "#111310",
    },
    DesignToken {
        name: "color.surface.inverse",
        token_type: "color",
        light: "#1A1C1A",
        dark: "#101310",
    },
    DesignToken {
        name: "color.text.primary",
        token_type: "color",
        light: "#1A1C1A",
        dark: "#F1F4EF",
    },
    DesignToken {
        name: "color.text.secondary",
        token_type: "color",
        light: "#39423C",
        dark: "#C4CCC5",
    },
    DesignToken {
        name: "color.text.muted",
        token_type: "color",
        light: "#626D65",
        dark: "#94A097",
    },
    DesignToken {
        name: "color.text.disabled",
        token_type: "color",
        light: "#657068",
        dark: "#737D76",
    },
    DesignToken {
        name: "color.text.on-accent",
        token_type: "color",
        light: "#FFFFFF",
        dark: "#102019",
    },
    DesignToken {
        name: "color.text.placeholder",
        token_type: "color",
        light: "#626D65",
        dark: "#94A097",
    },
    DesignToken {
        name: "color.text.inverse",
        token_type: "color",
        light: "#FFFFFF",
        dark: "#F1F4EF",
    },
    DesignToken {
        name: "color.accent.default",
        token_type: "color",
        light: "#216E52",
        dark: "#77C3A0",
    },
    DesignToken {
        name: "color.accent.hover",
        token_type: "color",
        light: "#185A45",
        dark: "#8FD3B4",
    },
    DesignToken {
        name: "color.accent.pressed",
        token_type: "color",
        light: "#185A45",
        dark: "#5CAF89",
    },
    DesignToken {
        name: "color.accent.subtle",
        token_type: "color",
        light: "#D7F1E5",
        dark: "#183A2D",
    },
    DesignToken {
        name: "color.control.hover",
        token_type: "color",
        light: "#EDF1EE",
        dark: "#2A2F29",
    },
    DesignToken {
        name: "color.control.pressed",
        token_type: "color",
        light: "#D7DED9",
        dark: "#37443B",
    },
    DesignToken {
        name: "color.control.disabled.background",
        token_type: "color",
        light: "#EDF1EE",
        dark: "#1A1D19",
    },
    DesignToken {
        name: "color.control.disabled.border",
        token_type: "color",
        light: "#D7DED9",
        dark: "#374039",
    },
    DesignToken {
        name: "color.selection.background",
        token_type: "color",
        light: "#D7F1E5",
        dark: "#183A2D",
    },
    DesignToken {
        name: "color.selection.border",
        token_type: "color",
        light: "#216E52",
        dark: "#77C3A0",
    },
    DesignToken {
        name: "color.search.match",
        token_type: "color",
        light: "#FFF0CC",
        dark: "#5A4316",
    },
    DesignToken {
        name: "color.search.match.active",
        token_type: "color",
        light: "#F1C470",
        dark: "#6A4C16",
    },
    DesignToken {
        name: "color.comment.highlight",
        token_type: "color",
        light: "#C7B5FF",
        dark: "#A88DFF",
    },
    DesignToken {
        name: "color.comment.active",
        token_type: "color",
        light: "#6D4AA2",
        dark: "#C9A8FF",
    },
    DesignToken {
        name: "color.comment.resolved",
        token_type: "color",
        light: "#2D7646",
        dark: "#83D9A1",
    },
    DesignToken {
        name: "color.comment.orphaned",
        token_type: "color",
        light: "#9A5B00",
        dark: "#E7B46E",
    },
    DesignToken {
        name: "color.status.success",
        token_type: "color",
        light: "#2D7646",
        dark: "#83D9A1",
    },
    DesignToken {
        name: "color.status.saving",
        token_type: "color",
        light: "#3578B8",
        dark: "#73B7F0",
    },
    DesignToken {
        name: "color.status.warning",
        token_type: "color",
        light: "#9A5B00",
        dark: "#F1C470",
    },
    DesignToken {
        name: "color.status.error",
        token_type: "color",
        light: "#A63D32",
        dark: "#FF9D8E",
    },
    DesignToken {
        name: "color.status.success.subtle",
        token_type: "color",
        light: "#DFF2E5",
        dark: "#173B29",
    },
    DesignToken {
        name: "color.status.saving.subtle",
        token_type: "color",
        light: "#DDEBFA",
        dark: "#1C3447",
    },
    DesignToken {
        name: "color.status.warning.subtle",
        token_type: "color",
        light: "#FFF0CC",
        dark: "#4D3A1B",
    },
    DesignToken {
        name: "color.status.error.subtle",
        token_type: "color",
        light: "#FBE2DF",
        dark: "#4A211E",
    },
    DesignToken {
        name: "color.destructive.default",
        token_type: "color",
        light: "#A63D32",
        dark: "#FF9D8E",
    },
    DesignToken {
        name: "color.destructive.subtle",
        token_type: "color",
        light: "#FBE2DF",
        dark: "#4A211E",
    },
    DesignToken {
        name: "color.overlay.scrim",
        token_type: "color",
        light: "#1A1C1A66",
        dark: "#00000099",
    },
    DesignToken {
        name: "size.ribbon.height",
        token_type: "sizing",
        light: "52",
        dark: "52",
    },
    DesignToken {
        name: "size.status.height",
        token_type: "sizing",
        light: "32",
        dark: "32",
    },
    DesignToken {
        name: "size.control.compact",
        token_type: "sizing",
        light: "28",
        dark: "28",
    },
    DesignToken {
        name: "size.control.default",
        token_type: "sizing",
        light: "36",
        dark: "36",
    },
    DesignToken {
        name: "size.icon.core",
        token_type: "sizing",
        light: "20",
        dark: "20",
    },
    DesignToken {
        name: "radius.default",
        token_type: "borderRadius",
        light: "4",
        dark: "4",
    },
    DesignToken {
        name: "border.default",
        token_type: "borderWidth",
        light: "1",
        dark: "1",
    },
    DesignToken {
        name: "border.focus",
        token_type: "borderWidth",
        light: "2",
        dark: "2",
    },
    DesignToken {
        name: "font.family.ui",
        token_type: "fontFamily",
        light: "Source Sans 3",
        dark: "Source Sans 3",
    },
    DesignToken {
        name: "font.family.prose.sample",
        token_type: "fontFamily",
        light: "Source Serif 4",
        dark: "Source Serif 4",
    },
    DesignToken {
        name: "font.family.code",
        token_type: "fontFamily",
        light: "ui-monospace, Menlo, Consolas, Liberation Mono",
        dark: "ui-monospace, Menlo, Consolas, Liberation Mono",
    },
];

/// Exact semantic roles that every appearance must provide.
pub const REQUIRED_SEMANTIC_ROLES: &[&str] = &[
    "color.canvas.application",
    "color.surface.sidebar",
    "color.surface.panel",
    "color.surface.manuscript",
    "color.surface.elevated",
    "color.text.primary",
    "color.text.secondary",
    "color.text.disabled",
    "color.border.default",
    "color.focus.ring",
    "color.accent.default",
    "color.selection.background",
    "color.status.error",
    "color.destructive.default",
    "color.overlay.scrim",
];
