[package]
name = "parchmint-search-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
parchmint-search-api = { path = "../parchmint-search-api" }
rusqlite = { version = "=0.40.1", default-features = false, features = ["bundled"] }
