[package]
name = "parchmint-save"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
parchmint-domain = { path = "../parchmint-domain" }
parchmint-history-api = { path = "../parchmint-history-api" }
parchmint-project-format = { path = "../parchmint-project-format" }
parchmint-project-repository = { path = "../parchmint-project-repository" }
parchmint-recovery-api = { path = "../parchmint-recovery-api" }
