#!/usr/bin/env bash
# Generate the ignored, host-specific Compose override used by the dev
# container. On Linux this forwards Wayland/X11, the session bus, GPU devices,
# SSH, Git configuration, and existing Codex/OpenCode state when available.

set -euo pipefail

devcontainer_dir="$(cd "$(dirname "$0")/../.devcontainer" && pwd)"
override="$devcontainer_dir/docker-compose.override.yml"
temporary="$(mktemp "$devcontainer_dir/docker-compose.override.yml.XXXXXX")"
trap 'rm -f "$temporary"' EXIT

yaml_quote() {
  local value=${1//\'/\'\'}
  printf "'%s'" "$value"
}

append_bind() {
  local source=$1
  local target=$2
  local read_only=${3:-false}

  printf '%s\n' \
    '      - type: bind' \
    "        source: $(yaml_quote "$source")" \
    "        target: $(yaml_quote "$target")" \
    "        read_only: $read_only" >>"$temporary"
}

path_is_within() {
  local path=$1
  local directory=${2%/}

  [[ -n $directory && $path == "$directory"/* ]]
}

host_system=$(uname -s)
host_runtime=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
wayland_display=${WAYLAND_DISPLAY:-}
xauthority=${XAUTHORITY:-$HOME/.Xauthority}
dbus_address=${DBUS_SESSION_BUS_ADDRESS:-}
ssh_auth_sock=${SSH_AUTH_SOCK:-}
share_host_state=${PARCHMINT_SHARE_HOST_STATE:-1}
force_software=${PARCHMINT_FORCE_SOFTWARE_RENDERING:-0}

has_runtime=false
has_wayland=false
has_x11=false
has_nvidia=false
has_xauthority=false
has_ssh_agent=false
device_groups=()
if [[ $host_system == Linux && -d $host_runtime ]]; then
  has_runtime=true
fi
if [[ $host_system == Linux && -n $wayland_display && -S $host_runtime/$wayland_display ]]; then
  has_wayland=true
fi
if [[ $host_system == Linux && -n ${DISPLAY:-} && -d /tmp/.X11-unix ]]; then
  has_x11=true
fi
if [[ $host_system == Linux ]] && command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
  has_nvidia=true
fi
if [[ $host_system == Linux && $force_software != 1 && -d /dev/dri ]]; then
  mapfile -t device_groups < <(find /dev/dri -maxdepth 1 -type c -printf '%G\n' | sort -un)
fi
if $has_x11 && [[ -f $xauthority ]]; then
  has_xauthority=true
fi
if [[ -n $ssh_auth_sock && -S $ssh_auth_sock ]]; then
  has_ssh_agent=true
fi

qpa_platform=offscreen
if $has_wayland && $has_x11; then
  qpa_platform='wayland;xcb'
elif $has_wayland; then
  qpa_platform=wayland
elif $has_x11; then
  qpa_platform=xcb
fi

cat >"$temporary" <<'EOF'
# Generated by scripts/detect-gpu.sh; do not edit or commit.
services:
  parchmint:
EOF

if ((${#device_groups[@]})); then
  printf '%s\n' \
    '    build:' \
    '      args:' \
    "        HOST_DRI_GIDS: $(yaml_quote "${device_groups[*]}")" >>"$temporary"
fi

cat >>"$temporary" <<EOF
    environment:
      QT_QPA_PLATFORM: $(yaml_quote "$qpa_platform")
EOF

if $has_runtime; then
  printf '%s\n' \
    "      XDG_RUNTIME_DIR: $(yaml_quote "$host_runtime")" >>"$temporary"
fi

if $has_wayland; then
  printf '%s\n' \
    "      WAYLAND_DISPLAY: $(yaml_quote "$wayland_display")" >>"$temporary"
fi

if [[ -n $dbus_address ]]; then
  printf '%s\n' \
    "      DBUS_SESSION_BUS_ADDRESS: $(yaml_quote "$dbus_address")" >>"$temporary"
fi

if $has_x11; then
  printf '%s\n' "      DISPLAY: $(yaml_quote "$DISPLAY")" >>"$temporary"
  if $has_xauthority; then
    printf '%s\n' "      XAUTHORITY: $(yaml_quote "$xauthority")" >>"$temporary"
  else
    printf '%s\n' \
      "Warning: X11 is available but no Xauthority file was found at $xauthority." \
      'X11 may require: xhost +si:localuser:$USER' >&2
  fi
fi

if $has_ssh_agent; then
  printf '%s\n' \
    "      SSH_AUTH_SOCK: $(yaml_quote "$ssh_auth_sock")" >>"$temporary"
fi

if [[ $force_software == 1 ]] || [[ $host_system != Linux ]] || { [[ ! -d /dev/dri ]] && ! $has_nvidia; }; then
  printf '%s\n' \
    "      QT_QUICK_BACKEND: 'software'" \
    "      LIBGL_ALWAYS_SOFTWARE: '1'" >>"$temporary"
fi

printf '%s\n' '    volumes:' >>"$temporary"

if $has_runtime; then
  # Keep the host path unchanged so attach-time remoteEnv values point directly
  # at the current Wayland, D-Bus, Xauthority, and SSH-agent endpoints.
  append_bind "$host_runtime" "$host_runtime" true
fi
if $has_x11; then
  append_bind /tmp/.X11-unix /tmp/.X11-unix true
  if $has_xauthority && ! path_is_within "$xauthority" "$host_runtime"; then
    # Traditional Xorg normally uses the stable $HOME/.Xauthority path. Keep
    # that live file available without copying its cookie.
    append_bind "$xauthority" "$xauthority" true
  fi
fi

if [[ $share_host_state == 1 ]]; then
  [[ -d $HOME/.codex ]] && append_bind "$HOME/.codex" /home/vscode/.codex false
  [[ -d $HOME/.config/opencode ]] && append_bind "$HOME/.config/opencode" /home/vscode/.config/opencode false
  [[ -d $HOME/.local/share/opencode ]] && append_bind "$HOME/.local/share/opencode" /home/vscode/.local/share/opencode false
  [[ -f $HOME/.gitconfig ]] && append_bind "$HOME/.gitconfig" /home/vscode/.gitconfig true
  [[ -d $HOME/.ssh ]] && append_bind "$HOME/.ssh" /home/vscode/.ssh false
fi

if $has_ssh_agent && ! path_is_within "$ssh_auth_sock" "$host_runtime"; then
  append_bind "$ssh_auth_sock" "$ssh_auth_sock" false
fi

if [[ $host_system == Linux && $force_software != 1 ]]; then
  if $has_nvidia; then
    cat >>"$temporary" <<'EOF'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
EOF
  elif [[ -d /dev/dri ]]; then
    printf '%s\n' \
      '    devices:' \
      '      - /dev/dri:/dev/dri' >>"$temporary"

    if ((${#device_groups[@]})); then
      printf '%s\n' '    group_add:' >>"$temporary"
      printf "      - '%s'\n" "${device_groups[@]}" >>"$temporary"
    fi
  fi
fi

mv "$temporary" "$override"
trap - EXIT

rendering=hardware
if [[ $force_software == 1 ]] || [[ $host_system != Linux ]] || { [[ ! -d /dev/dri ]] && ! $has_nvidia; }; then
  rendering=software
fi
printf 'Wrote %s (%s display, %s rendering).\n' "$override" "$qpa_platform" "$rendering"
