#!/usr/bin/env bash
# Generate the ignored, host-specific Compose override used by the dev
# container. On Linux this forwards Wayland/X11, the session bus, GPU devices,
# SSH, Git configuration, and existing Codex/OpenCode state when available.

set -euo pipefail

devcontainer_dir="$(cd "$(dirname "$0")/../.devcontainer" && pwd)"
override="$devcontainer_dir/docker-compose.override.yml"
temporary="$(mktemp "$devcontainer_dir/docker-compose.override.yml.XXXXXX")"
trap 'rm -f "$temporary"' EXIT

yaml_quote() {
  local value=${1//\'/\'\'}
  printf "'%s'" "$value"
}

append_bind() {
  local source=$1
  local target=$2
  local read_only=${3:-false}

  printf '%s\n' \
    '      - type: bind' \
    "        source: $(yaml_quote "$source")" \
    "        target: $(yaml_quote "$target")" \
    "        read_only: $read_only" >>"$temporary"
}

host_system=$(uname -s)
host_runtime=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
wayland_display=${WAYLAND_DISPLAY:-}
xauthority=${XAUTHORITY:-$HOME/.Xauthority}
share_host_state=${PARCHMINT_SHARE_HOST_STATE:-1}
force_software=${PARCHMINT_FORCE_SOFTWARE_RENDERING:-0}

has_wayland=false
has_x11=false
has_nvidia=false
device_groups=()
if [[ $host_system == Linux && -n $wayland_display && -S $host_runtime/$wayland_display ]]; then
  has_wayland=true
fi
if [[ $host_system == Linux && -n ${DISPLAY:-} && -d /tmp/.X11-unix ]]; then
  has_x11=true
fi
if [[ $host_system == Linux ]] && command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
  has_nvidia=true
fi
if [[ $host_system == Linux && $force_software != 1 && -d /dev/dri ]]; then
  mapfile -t device_groups < <(find /dev/dri -maxdepth 1 -type c -printf '%G\n' | sort -un)
fi

qpa_platform=offscreen
if $has_wayland && $has_x11; then
  qpa_platform='wayland;xcb'
elif $has_wayland; then
  qpa_platform=wayland
elif $has_x11; then
  qpa_platform=xcb
fi

cat >"$temporary" <<'EOF'
# Generated by scripts/detect-gpu.sh; do not edit or commit.
services:
  parchmint:
EOF

if ((${#device_groups[@]})); then
  printf '%s\n' \
    '    build:' \
    '      args:' \
    "        HOST_DRI_GIDS: $(yaml_quote "${device_groups[*]}")" >>"$temporary"
fi

cat >>"$temporary" <<EOF
    environment:
      QT_QPA_PLATFORM: $(yaml_quote "$qpa_platform")
EOF

if $has_wayland; then
  printf '%s\n' \
    "      WAYLAND_DISPLAY: $(yaml_quote "$wayland_display")" \
    "      XDG_RUNTIME_DIR: '/tmp/parchmint-runtime'" >>"$temporary"
  if [[ -S $host_runtime/bus ]]; then
    printf '%s\n' \
      "      DBUS_SESSION_BUS_ADDRESS: 'unix:path=/tmp/parchmint-runtime/bus'" >>"$temporary"
  fi
fi

if $has_x11; then
  printf '%s\n' "      DISPLAY: $(yaml_quote "$DISPLAY")" >>"$temporary"
  if [[ -f $xauthority ]]; then
    printf '%s\n' "      XAUTHORITY: '/tmp/parchmint-xauthority'" >>"$temporary"
  else
    printf '%s\n' \
      "Warning: X11 is available but no Xauthority file was found at $xauthority." \
      'X11 may require: xhost +si:localuser:$USER' >&2
  fi
fi

if [[ -n ${SSH_AUTH_SOCK:-} && -S $SSH_AUTH_SOCK ]]; then
  printf '%s\n' \
    "      SSH_AUTH_SOCK: '/tmp/parchmint-ssh-agent'" >>"$temporary"
fi

if [[ $force_software == 1 ]] || [[ $host_system != Linux ]] || { [[ ! -d /dev/dri ]] && ! $has_nvidia; }; then
  printf '%s\n' \
    "      QT_QUICK_BACKEND: 'software'" \
    "      LIBGL_ALWAYS_SOFTWARE: '1'" >>"$temporary"
fi

printf '%s\n' '    volumes:' >>"$temporary"

if $has_wayland; then
  append_bind "$host_runtime" /tmp/parchmint-runtime true
fi
if $has_x11; then
  append_bind /tmp/.X11-unix /tmp/.X11-unix true
  if [[ -f $xauthority ]]; then
    append_bind "$xauthority" /tmp/parchmint-xauthority true
  fi
fi

if [[ $share_host_state == 1 ]]; then
  [[ -d $HOME/.codex ]] && append_bind "$HOME/.codex" /home/vscode/.codex false
  [[ -d $HOME/.config/opencode ]] && append_bind "$HOME/.config/opencode" /home/vscode/.config/opencode false
  [[ -d $HOME/.local/share/opencode ]] && append_bind "$HOME/.local/share/opencode" /home/vscode/.local/share/opencode false
  [[ -f $HOME/.gitconfig ]] && append_bind "$HOME/.gitconfig" /home/vscode/.gitconfig true
  [[ -d $HOME/.ssh ]] && append_bind "$HOME/.ssh" /home/vscode/.ssh false
fi

if [[ -n ${SSH_AUTH_SOCK:-} && -S $SSH_AUTH_SOCK ]]; then
  append_bind "$SSH_AUTH_SOCK" /tmp/parchmint-ssh-agent false
fi

if [[ $host_system == Linux && $force_software != 1 ]]; then
  if $has_nvidia; then
    cat >>"$temporary" <<'EOF'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
EOF
  elif [[ -d /dev/dri ]]; then
    printf '%s\n' \
      '    devices:' \
      '      - /dev/dri:/dev/dri' >>"$temporary"

    if ((${#device_groups[@]})); then
      printf '%s\n' '    group_add:' >>"$temporary"
      printf "      - '%s'\n" "${device_groups[@]}" >>"$temporary"
    fi
  fi
fi

mv "$temporary" "$override"
trap - EXIT

rendering=hardware
if [[ $force_software == 1 ]] || [[ $host_system != Linux ]] || { [[ ! -d /dev/dri ]] && ! $has_nvidia; }; then
  rendering=software
fi
printf 'Wrote %s (%s display, %s rendering).\n' "$override" "$qpa_platform" "$rendering"
